name: verify
on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: install x11
        run: sudo apt install -y libx11-dev

      - uses: actions/setup-go@v6
        with:
          go-version: "1.25"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.6.2
          verify: false

  # test:
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest, macos-latest]
  #   runs-on: ${{ matrix.os }}
  #   steps:
  #     - uses: actions/checkout@v4

  #     - uses: actions/setup-go@v6
  #       with:
  #         go-version: "1.25"

  #     - name: test
  #       run: go test ./...
