name: verify
on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: install x11
        run: sudo apt install -y libx11-dev xorg

      - uses: actions/setup-go@v6
        with:
          go-version: "1.25"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.6.2
          verify: false

  test:
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest, macos-latest]
        os: [ubuntu-latest]
        compiler: [gcc, clang]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: install x11
        run: sudo apt install -y libx11-dev xorg

      - uses: actions/setup-go@v6
        with:
          go-version: "1.25"

      - name: test
        env:
          CC: ${{ matrix.compiler }}
          CXX: ${{ matrix.compiler }}++
        run: go test ./...
